### ISSUE TITLE
Target_dir vs Backup_dir

### ISSUE THREAD

**Issue by miketweaver** [todiadiyatmo/bash-backup-rotation-script#1]
```
# The directory to be backup , DO NOT END THE DIRECTORY WITH BACKSLASH !
TARGET_DIR=/target_directory
# The backup directory , DO NOT END THE DIRECTORY WITH BACKSLASH !
BACKUP_DIR=/copy_target_to_backup_directory
```

I think these are hard to understand. I would normally think the target directory should be where you want the files to go, and the backup directory to be the files that are being backed up. 

Switching them and adding some extra words would make more sense:

```
# The directory where the files to be backed up are located DO NOT END THE DIRECTORY WITH BACKSLASH !
BACKUP_DIR=/backup_directory

# The directory where the backups are sent , DO NOT END THE DIRECTORY WITH BACKSLASH !
TARGET_DIR=/copy_backup_directory_to_here
```

Note: you will have to go through the script and switch them as well. It's not that many though.

**Comment by todiadiyatmo** [comment]
@miketweaver  hi, your update are merged !
