### ISSUE TITLE
Issue uploading to FTP 

### ISSUE THREAD

**Issue by smmalloy** [todiadiyatmo/bash-backup-rotation-script#2]
Hi, firstly thanks for writing this script!

I have the following issue while trying to get the file to send via FTP: 

'Using binary mode to transfer files.
550 Can't create directory: File exists
250 OK. Current directory is /backups
200 TYPE is now 8-bit binary
local: /home/backup/backup.incoming/04-05-2015-daily.tgz remote: .
200 PORT command successful
553 Can't open that file: Is a directory
221-Goodbye. You uploaded 0 and downloaded 0 kbytes.
221 Logout.'

Thanks

**Comment by miketweaver** [comment]
Sure thing. Give me a bit to look at it.

**Comment by todiadiyatmo** [comment]
Hi could you try the new version

**Comment by todiadiyatmo** [comment]
fixed on https://github.com/todiadiyatmo/bash-backup-rotation-script/commit/fbc8abf6bd149833a4720e9e52a62483f71db756
